# Generated by Django 3.1.3 on 2021-01-19 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nip', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('implementation_date', models.DateTimeField()),
                ('data_of_placing_the_order', models.DateTimeField()),
                ('status', models.CharField(choices=[('Submitted', 'submitted'), ('Not submitted', 'not_submitted')], max_length=13)),
                ('order_value', models.DecimalField(decimal_places=2, max_digits=30)),
                ('contractor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.contractor')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('full_price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('product_id', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='orders.order')),
            ],
        ),
    ]
